name: Running tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Step 1 - Checkout code
      uses: actions/checkout@v3

    - name: Step 2 - Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'adopt'

    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml

    # install chrome browser
    - name: Step 4 - Install Chrome
      run: sudo apt-get install -y google-chrome-stable

    # run main file
    - name: Step 5 - Run main file
      run: mvn test -Dtest=com.peviitor.main
