name: Running tests

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: windows-latest
    steps:
    - name: Step 1 - Checkout code
      uses: actions/checkout@v3

    - name: Step 2 - Set up Java
      uses: actions/setup-java@v3
      with:
        java-version: '11'

    - name: Step 3 - Build with Maven
      run: mvn -B package --file pom.xml

    # run main file
    - name: Step 4 - Run main file
      run: java src/test/java/com/peviitor/app/main.java
